# Tools-Numpy

Numpy is a Fundamental Library for Scientific Computing in Python. It is Centered Around a Powerfull N-Dimensional Array and it also Have Some Useful Linear Algebra Concepts, Fourier Transforms and Number Functions.

# Creating Arrays

Now Let's Import `Numpy` Most People Import it as `np`.

In [1]:
import numpy as np

## `np.zeros`

The zeros Function Takes an `n` argument and Creates an Array Which has `n` number of zeros.

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

We Can also Create a 2D Array(a matrix) With Same Just Pass Dimension of Array on the place of `n`.

In [3]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Some Vocabulary
* In NumPy, each dimension is called an **axis**.
* The number of axes is called the **rank**.
    * For example, the above 3x4 matrix is an array of rank 2 (it is 2-dimensional).
    * The first axis has length 3, the second has length 4.
* An array's list of axis lengths is called the **shape** of the array.
    * For example, the above matrix's shape is `(3, 4)`.
    * The rank is equal to the shape's length.
* The **size** of an array is the total number of elements, which is the product of all axis lengths (eg. 3*4=12)

Now Let's Store This Array into a Varible Named `a`

In [4]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
a.shape

(3, 4)

In [6]:
a.ndim # Equal to len(a.shape)

2

In [7]:
a.size

12