# Tools-Numpy

Numpy is a Fundamental Library for Scientific Computing in Python. It is Centered Around a Powerfull N-Dimensional Array and it also Have Some Useful Linear Algebra Concepts, Fourier Transforms and Number Functions.

# Creating Arrays

Now Let's Import `Numpy` Most People Import it as `np`.

In [1]:
import numpy as np

## `np.zeros`

The zeros Function Takes an `n` argument and Creates an Array Which has `n` number of zeros.

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

We Can also Create a 2D Array(a matrix) With Same Just Pass Dimension of Array on the place of `n`.

In [3]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Some Vocabulary
* In NumPy, each dimension is called an **axis**.
* The number of axes is called the **rank**.
    * For example, the above 3x4 matrix is an array of rank 2 (it is 2-dimensional).
    * The first axis has length 3, the second has length 4.
* An array's list of axis lengths is called the **shape** of the array.
    * For example, the above matrix's shape is `(3, 4)`.
    * The rank is equal to the shape's length.
* The **size** of an array is the total number of elements, which is the product of all axis lengths (eg. 3*4=12)

Now Let's Store This Array into a Varible Named `a`

In [4]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
a.shape

(3, 4)

In [6]:
a.ndim # Equal to len(a.shape)

2

In [7]:
a.size

12

## N-Dimensional Array

You can Also Create N-Dimensional Array For Example Here is a 3DArray(`rank=3`), with `shape=(2, 3, 4)`.

In [8]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## Type of Array

In [9]:
type(np.zeros((3, 4)))

numpy.ndarray

Numpy Arrays have a Special Type known as `ndarray`

## `np.ones`

Many other NumPy functions create `ndarrays`.

Here's a 3x4 matrix full of ones:

In [10]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## `np.full`
Creates an Array of the Given Shape Intialized with the Given Value. Here's  a 3x4 matrix full of `π`.

In [11]:
np.full((3,4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

## `np.empty`

Creates an Array of Given Dimension In Which Values are not Predictable.

In [12]:
np.empty((2, 3))

array([[4.63999373e-310, 0.00000000e+000, 6.91386137e-310],
       [6.91389027e-310, 6.91386138e-310, 6.91389027e-310]])

## `np.array`
You Can Create an Custom Array Using np.array function.

In [13]:
np.array([[1, 2, 3, 4], [10, 20, 30, 40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

## `np.arange`

You can Create Numpy Array with `np.arange` function Which Works as Same As pythons `range` function.

In [14]:
np.arange(1, 5)

array([1, 2, 3, 4])

It Also Works With Floats

In [15]:
np.arange(1.0, 5.0)

array([1., 2., 3., 4.])

You Can Also Provide Step Parameters.

In [16]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])